# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import distrifs_pb2 as distrifs__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in distrifs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDataNode = channel.unary_unary(
                '/distrifs.MasterService/RegisterDataNode',
                request_serializer=distrifs__pb2.RegisterDataNodeRequest.SerializeToString,
                response_deserializer=distrifs__pb2.RegisterDataNodeReply.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/distrifs.MasterService/Heartbeat',
                request_serializer=distrifs__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=distrifs__pb2.HeartbeatReply.FromString,
                _registered_method=True)
        self.BlockReport = channel.unary_unary(
                '/distrifs.MasterService/BlockReport',
                request_serializer=distrifs__pb2.BlockReportRequest.SerializeToString,
                response_deserializer=distrifs__pb2.BlockReportReply.FromString,
                _registered_method=True)
        self.Mkdir = channel.unary_unary(
                '/distrifs.MasterService/Mkdir',
                request_serializer=distrifs__pb2.MkdirRequest.SerializeToString,
                response_deserializer=distrifs__pb2.MkdirReply.FromString,
                _registered_method=True)
        self.Ls = channel.unary_unary(
                '/distrifs.MasterService/Ls',
                request_serializer=distrifs__pb2.LsRequest.SerializeToString,
                response_deserializer=distrifs__pb2.LsReply.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/distrifs.MasterService/Stat',
                request_serializer=distrifs__pb2.StatRequest.SerializeToString,
                response_deserializer=distrifs__pb2.StatReply.FromString,
                _registered_method=True)
        self.Rm = channel.unary_unary(
                '/distrifs.MasterService/Rm',
                request_serializer=distrifs__pb2.RmRequest.SerializeToString,
                response_deserializer=distrifs__pb2.RmReply.FromString,
                _registered_method=True)
        self.Mv = channel.unary_unary(
                '/distrifs.MasterService/Mv',
                request_serializer=distrifs__pb2.MvRequest.SerializeToString,
                response_deserializer=distrifs__pb2.MvReply.FromString,
                _registered_method=True)
        self.AssignChunk = channel.unary_unary(
                '/distrifs.MasterService/AssignChunk',
                request_serializer=distrifs__pb2.AssignChunkRequest.SerializeToString,
                response_deserializer=distrifs__pb2.AssignChunkReply.FromString,
                _registered_method=True)
        self.CommitChunk = channel.unary_unary(
                '/distrifs.MasterService/CommitChunk',
                request_serializer=distrifs__pb2.CommitChunkRequest.SerializeToString,
                response_deserializer=distrifs__pb2.CommitChunkReply.FromString,
                _registered_method=True)
        self.GetFilePlan = channel.unary_unary(
                '/distrifs.MasterService/GetFilePlan',
                request_serializer=distrifs__pb2.GetFilePlanRequest.SerializeToString,
                response_deserializer=distrifs__pb2.GetFilePlanReply.FromString,
                _registered_method=True)


class MasterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDataNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mkdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFilePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDataNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDataNode,
                    request_deserializer=distrifs__pb2.RegisterDataNodeRequest.FromString,
                    response_serializer=distrifs__pb2.RegisterDataNodeReply.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=distrifs__pb2.HeartbeatRequest.FromString,
                    response_serializer=distrifs__pb2.HeartbeatReply.SerializeToString,
            ),
            'BlockReport': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockReport,
                    request_deserializer=distrifs__pb2.BlockReportRequest.FromString,
                    response_serializer=distrifs__pb2.BlockReportReply.SerializeToString,
            ),
            'Mkdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkdir,
                    request_deserializer=distrifs__pb2.MkdirRequest.FromString,
                    response_serializer=distrifs__pb2.MkdirReply.SerializeToString,
            ),
            'Ls': grpc.unary_unary_rpc_method_handler(
                    servicer.Ls,
                    request_deserializer=distrifs__pb2.LsRequest.FromString,
                    response_serializer=distrifs__pb2.LsReply.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=distrifs__pb2.StatRequest.FromString,
                    response_serializer=distrifs__pb2.StatReply.SerializeToString,
            ),
            'Rm': grpc.unary_unary_rpc_method_handler(
                    servicer.Rm,
                    request_deserializer=distrifs__pb2.RmRequest.FromString,
                    response_serializer=distrifs__pb2.RmReply.SerializeToString,
            ),
            'Mv': grpc.unary_unary_rpc_method_handler(
                    servicer.Mv,
                    request_deserializer=distrifs__pb2.MvRequest.FromString,
                    response_serializer=distrifs__pb2.MvReply.SerializeToString,
            ),
            'AssignChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignChunk,
                    request_deserializer=distrifs__pb2.AssignChunkRequest.FromString,
                    response_serializer=distrifs__pb2.AssignChunkReply.SerializeToString,
            ),
            'CommitChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitChunk,
                    request_deserializer=distrifs__pb2.CommitChunkRequest.FromString,
                    response_serializer=distrifs__pb2.CommitChunkReply.SerializeToString,
            ),
            'GetFilePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilePlan,
                    request_deserializer=distrifs__pb2.GetFilePlanRequest.FromString,
                    response_serializer=distrifs__pb2.GetFilePlanReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distrifs.MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distrifs.MasterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDataNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/RegisterDataNode',
            distrifs__pb2.RegisterDataNodeRequest.SerializeToString,
            distrifs__pb2.RegisterDataNodeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/Heartbeat',
            distrifs__pb2.HeartbeatRequest.SerializeToString,
            distrifs__pb2.HeartbeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/BlockReport',
            distrifs__pb2.BlockReportRequest.SerializeToString,
            distrifs__pb2.BlockReportReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mkdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/Mkdir',
            distrifs__pb2.MkdirRequest.SerializeToString,
            distrifs__pb2.MkdirReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/Ls',
            distrifs__pb2.LsRequest.SerializeToString,
            distrifs__pb2.LsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/Stat',
            distrifs__pb2.StatRequest.SerializeToString,
            distrifs__pb2.StatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/Rm',
            distrifs__pb2.RmRequest.SerializeToString,
            distrifs__pb2.RmReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/Mv',
            distrifs__pb2.MvRequest.SerializeToString,
            distrifs__pb2.MvReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/AssignChunk',
            distrifs__pb2.AssignChunkRequest.SerializeToString,
            distrifs__pb2.AssignChunkReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/CommitChunk',
            distrifs__pb2.CommitChunkRequest.SerializeToString,
            distrifs__pb2.CommitChunkReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFilePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.MasterService/GetFilePlan',
            distrifs__pb2.GetFilePlanRequest.SerializeToString,
            distrifs__pb2.GetFilePlanReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataNodeControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CopyChunk = channel.unary_unary(
                '/distrifs.DataNodeControl/CopyChunk',
                request_serializer=distrifs__pb2.CopyChunkRequest.SerializeToString,
                response_deserializer=distrifs__pb2.ControlStatus.FromString,
                _registered_method=True)
        self.DeleteChunk = channel.unary_unary(
                '/distrifs.DataNodeControl/DeleteChunk',
                request_serializer=distrifs__pb2.DeleteChunkRequest.SerializeToString,
                response_deserializer=distrifs__pb2.ControlStatus.FromString,
                _registered_method=True)


class DataNodeControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CopyChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CopyChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyChunk,
                    request_deserializer=distrifs__pb2.CopyChunkRequest.FromString,
                    response_serializer=distrifs__pb2.ControlStatus.SerializeToString,
            ),
            'DeleteChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChunk,
                    request_deserializer=distrifs__pb2.DeleteChunkRequest.FromString,
                    response_serializer=distrifs__pb2.ControlStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distrifs.DataNodeControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distrifs.DataNodeControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataNodeControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CopyChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.DataNodeControl/CopyChunk',
            distrifs__pb2.CopyChunkRequest.SerializeToString,
            distrifs__pb2.ControlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distrifs.DataNodeControl/DeleteChunk',
            distrifs__pb2.DeleteChunkRequest.SerializeToString,
            distrifs__pb2.ControlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

